### ISSUE TITLE
Errors on trying to add couple documents with same properties which different types

### ISSUE THREAD

**Issue by pushnitsa** [VirtoCommerce/vc-module-elastic-search#16]
Indexing issue. If products have the different typed properties with equal names, which we have in sample data.
![image](https://user-images.githubusercontent.com/15198683/81420122-c0202f00-914f-11ea-8a84-78d65d5323eb.png)
![image](https://user-images.githubusercontent.com/15198683/81420213-ee057380-914f-11ea-97cd-4c9fb86a79a0.png)
Sometimes could happened indexing issues like this (sometimes, because i suppose, ids is randomly generated and sort in DB table by primary key):
![property_adding_bug](https://user-images.githubusercontent.com/15198683/81420283-0ecdc900-9150-11ea-902f-9ac418968696.gif)
To demonstrate this issue, i've added PRwith unit test https://github.com/VirtoCommerce/vc-module-elastic-search/pull/15

Most likely problem in caching of field types while indexing.

**Comment by lnetrebskii** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-2255 has been created

**Comment by Woland2k** [comment]
I get the same error on dev environment with sample data
