### ISSUE TITLE
Add support of Elastic Search 7

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-module-elastic-search#7]
Currently indexation fails because of breaking changes which was made in 7 version

**Comment by dimitri-ak** [comment]
@VirtoCommerce/virto-commerce Is it possible to process this request in the near future?

**Comment by 5309** [comment]
Put it to the queue for further prioritization

**Comment by yecli** [comment]
Released: https://github.com/VirtoCommerce/vc-module-elastic-search/releases/tag/v1.2.1
