### ISSUE TITLE
Module forces ElasticSearch to use standard analizer for all fields.

### ISSUE THREAD

**Issue by IvanSalov** [VirtoCommerce/vc-module-elastic-search#8]
I'm trying to use synonym filter with custom analyzer on some index fields, but I can't because module specifies standard analyzer usage in search query. First part of query generated by module for search looks like this:
```
{
  {
    {
    "from": 0,
    "size": 4,
    "query": {
        "multi_match": {
            "query": "some_search_expression",
            "fields": [
                "__content^1.0"
            ],
            "type": "best_fields",
            "operator": "AND",
            "analyzer": "standard",
            "slop": 0,
            "prefix_length": 0,
            "max_expansions": 50,
            "lenient": false,
            "zero_terms_query": "NONE",
            "boost": 1
        }
    }
}
```
standard analyzer in query says that ES will use it for search on each field, even if they have custom analyzer in mapping.
Standard analyzer for query is specified in `ElasticSearchRequestBuilder.GetQuery` method. I think it should be removed, since it doesn't allow to use custom analyzers for search properly.
According to [https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis.html](url):

> The analyzer to use to search a particular field is determined by looking for:
> An analyzer specified in the query itself.
> The search_analyzer mapping parameter.
> The analyzer mapping parameter.
> An analyzer in the index settings called default_search.
> An analyzer in the index settings called default.
> The standard analyzer.

That means standard analyzer will be used anyway if no analyzer is specified for field or there is no default analyzer. Thus, old search logic will remain for all fields which have no analyzer in mapping.

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog.
https://virtocommerce.atlassian.net/browse/PRD-47
